In [1]:
import pandas as pd
import pyreadstat

In [2]:
infl, meta = pyreadstat.read_dta("D:/Dissertation(!)/Paper 3/inflation_6_21.dta")
print(infl.shape)
infl.head()

(353, 3)

   l_year  l_month  inflation_6_21
0    1992        1            1.97
1    1992        2            1.96
2    1992        3            1.95
3    1992        4            1.95
4    1992        5            1.94

In [3]:
df = pd.read_parquet("../data/processed/assembled.parquet")
print(df.shape)
df.head()

(327747, 58)

,geopin,move_in,move_out,purchase_price,sale_price,name,type,zoningclassification,zoningdescription,acres,...,income_tract_2010,percent_white_2010,percent_black_2010,percent_other_race_2010,percent_white_2000_homeowner,percent_black_2000_homeowner,percent_other_2000_homeowner,percent_white_2010_homeowner,percent_black_2010_homeowner,percent_other_2010_homeowner
0,41049784,9009,9065.0,NaN,NaN,Joseph,Street,HU-RD2,Historic Urban Two-Family Residential District,0.068965,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41049784,9065,11893.0,NaN,NaN,Joseph,Street,HU-RD2,Historic Urban Two-Family Residential District,0.068965,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41049784,11893,15931.0,NaN,0.0,Joseph,Street,HU-RD2,Historic Urban Two-Family Residential District,0.068965,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,41049784,15931,15964.0,0.0,0.0,Joseph,Street,HU-RD2,Historic Urban Two-Family Residential District,0.068965,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,41049784,15964,19184.0,0.0,495957.0,Joseph,Street,HU-RD2,Historic Urban Two-Family Residential District,0.068965,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print(df['l_date'].dtype)
print(df['l_date'].dropna().head(10))

float64
6     15281.0
10    14221.0
11    15705.0
14    18221.0
15    18962.0
20    12689.0
21    15643.0
26    15932.0
27    15932.0
29    19697.0
Name: l_date, dtype: float64